name: Docker build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build image and deploy for the api
      with:
        image: burka/luna_api
        tags: v0a,
        registry: docker.io
        directory: api
        dockerfile: api/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build image and deploy for the frontend
      with:
        image: burka/luna_frontend
        tags: v0a,
        registry: docker.io
        directory: frontend
        dockerfile: frontend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}